"""
Utils for cryptocurrencies addresses.
"""
BITCOIN_BECH32_PREFIX = 'bc1'
BITCOIN_P2PKH_PREFIX = '1'
BITCOIN_P2SH_PREFIX = '3'
HEX_PREFIX = '0x'
LITECOIN_BECH32_PREFIX = 'ltc1'
LITECOIN_P2PKH_PREFIX = 'L'
LITECOIN_P2SH_PREFIX = 'M'
MIN_BITCOIN_ADDRESS_LENGTH = 34
MIN_LITECOIN_ADDRESS_LENGTH = 34
REQUIRED_BITCOIN_ADDRESS_LENGTH = 42
REQUIRED_ETHEREUM_ADDRESS_LENGTH = 42
REQUIRED_LITECOIN_ADDRESS_LENGTH = 42
